import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const arquero = JSON.parse(readFileSync("paper/data/arquero-25k.json", "utf8"));
const pandas = JSON.parse(readFileSync("paper/data/pandas-compare-25k.json", "utf8"));
const wasm = JSON.parse(readFileSync("paper/data/wasm-ablation.json", "utf8"));
const fresh = JSON.parse(readFileSync("paper/data/fresh-process-ablation.json", "utf8"));
const conformance = JSON.parse(readFileSync("paper/data/conformance/summary.json", "utf8"));
const packageSize = JSON.parse(readFileSync("paper/data/package-size.json", "utf8"));

function geometricMean(values: number[]): number {
  return Math.exp(values.reduce((sum, value) => sum + Math.log(value), 0) / values.length);
}

function percentile(values: number[], q: number): number {
  const sorted = [...values].sort((a, b) => a - b);
  const position = (sorted.length - 1) * q;
  const lower = Math.floor(position);
  const upper = Math.ceil(position);
  if (lower === upper) return sorted[lower];
  return sorted[lower] * (upper - position) + sorted[upper] * (position - lower);
}

function familyFor(name: string): string {
  if (name.startsWith("merge_")) return "merge";
  if (name.startsWith("value_counts_")) return "value_counts";
  if (name.includes("groupby_")) return "groupby";
  return "sort_filter";
}

function summarizeRatios(entries: { case: string; ratio: number }[]) {
  return {
    cases: entries.length,
    bunPandaWins: entries.filter((entry) => entry.ratio < 1).length,
    ties: entries.filter((entry) => Math.abs(entry.ratio - 1) < 1e-9).length,
    comparatorWins: entries.filter((entry) => entry.ratio > 1).length,
    geometricMeanSpeedup: geometricMean(entries.map((entry) => 1 / entry.ratio)),
    medianSpeedup: percentile(entries.map((entry) => 1 / entry.ratio), 0.5),
    p10Speedup: percentile(entries.map((entry) => 1 / entry.ratio), 0.1),
    p90Speedup: percentile(entries.map((entry) => 1 / entry.ratio), 0.9),
  };
}

const arqueroEntries = arquero.results.map((entry: Record<string, number | string>) => ({
  case: String(entry.case),
  ratio: Number(entry.ratio),
}));
const familyNames = ["groupby", "sort_filter", "value_counts", "merge"];
const arqueroFamilies = Object.fromEntries(
  familyNames.map((family) => [
    family,
    summarizeRatios(arqueroEntries.filter((entry) => familyFor(entry.case) === family)),
  ])
);

const pandasEntries = pandas.results.map((entry: Record<string, number | string>) => ({
  case: String(entry.case),
  ratio: Number(entry.ratio),
}));

const wasmByCase = Object.fromEntries(
  ["groupby_fused_4", "sort_numeric_full", "sort_numeric_top1000", "filter_boolean_mask"].map(
    (caseName) => [
      caseName,
      Object.fromEntries(
        wasm.results
          .filter((entry: Record<string, number | string>) => entry.case === caseName)
          .map((entry: Record<string, number | string>) => [String(entry.rows), Number(entry.speedup)])
      ),
    ]
  )
);

const summary = {
  generatedAt: new Date().toISOString(),
  arquero: {
    rows: arquero.rows,
    iterations: arquero.iterations,
    rounds: arquero.rounds,
    overall: summarizeRatios(arqueroEntries),
    families: arqueroFamilies,
  },
  pandas: {
    rows: pandas.rows,
    cases: pandasEntries.length,
    overall: summarizeRatios(pandasEntries),
  },
  wasm: wasmByCase,
  freshProcess: fresh.cells,
  conformance: conformance.comparisons,
  packageSize: packageSize.artifacts,
};

mkdirSync("paper/data", { recursive: true });
writeFileSync("paper/data/summary.json", `${JSON.stringify(summary, null, 2)}\n`, "utf8");

const a = summary.arquero;
const p = summary.pandas;
const f = a.families;
const b = summary.packageSize;
const semantic = conformance.comparisons[0];
const backend = conformance.comparisons[1];
const freshIterations = fresh.raw.reduce(
  (total: number, entry: { samplesMs: number[] }) => total + entry.samplesMs.length,
  0
);
const tex = `% Generated by paper/artifact/summarize-study.ts; do not edit manually.
\\newcommand{\\ApiCount}{505}
\\newcommand{\\ArqueroCases}{${a.overall.cases}}
\\newcommand{\\ArqueroWins}{${a.overall.bunPandaWins}}
\\newcommand{\\ArqueroGeoSpeedup}{${a.overall.geometricMeanSpeedup.toFixed(2)}}
\\newcommand{\\GroupbyGeoSpeedup}{${f.groupby.geometricMeanSpeedup.toFixed(2)}}
\\newcommand{\\SortGeoSpeedup}{${f.sort_filter.geometricMeanSpeedup.toFixed(2)}}
\\newcommand{\\CountsGeoSpeedup}{${f.value_counts.geometricMeanSpeedup.toFixed(2)}}
\\newcommand{\\MergeGeoSpeedup}{${f.merge.geometricMeanSpeedup.toFixed(2)}}
\\newcommand{\\PandasCases}{${p.cases}}
\\newcommand{\\PandasWins}{${p.overall.bunPandaWins}}
\\newcommand{\\PandasGeoSpeedup}{${p.overall.geometricMeanSpeedup.toFixed(2)}}
\\newcommand{\\WasmSortMin}{${Math.min(...Object.values(wasmByCase.sort_numeric_full) as number[]).toFixed(2)}}
\\newcommand{\\WasmSortMax}{${Math.max(...Object.values(wasmByCase.sort_numeric_full) as number[]).toFixed(2)}}
\\newcommand{\\WasmFilterMin}{${Math.min(...Object.values(wasmByCase.filter_boolean_mask) as number[]).toFixed(2)}}
\\newcommand{\\WasmFilterMax}{${Math.max(...Object.values(wasmByCase.filter_boolean_mask) as number[]).toFixed(2)}}
\\newcommand{\\FreshProcesses}{${fresh.raw.length.toLocaleString("en-US")}}
\\newcommand{\\FreshIterations}{${freshIterations.toLocaleString("en-US")}}
\\newcommand{\\ConformanceCases}{${semantic.total.toLocaleString("en-US")}}
\\newcommand{\\ConformancePasses}{${semantic.passed.toLocaleString("en-US")}}
\\newcommand{\\ConformancePercent}{${(semantic.agreement * 100).toFixed(2)}}
\\newcommand{\\BackendCases}{${backend.total.toLocaleString("en-US")}}
\\newcommand{\\BackendPasses}{${backend.passed.toLocaleString("en-US")}}
\\newcommand{\\NpmTarballKiB}{${(b.npmTarballBytes / 1024).toFixed(1)}}
\\newcommand{\\NpmUnpackedKiB}{${(b.npmUnpackedBytes / 1024).toFixed(1)}}
\\newcommand{\\NpmEntryCount}{${b.npmEntryCount}}
\\newcommand{\\CoreBundleKiB}{${(b.coreMinifiedBundleBytes / 1024).toFixed(1)}}
\\newcommand{\\CoreBundleGzipKiB}{${(b.coreMinifiedBundleGzipBytes / 1024).toFixed(1)}}
\\newcommand{\\WasmBytes}{${b.wasmBinaryBytes.toLocaleString("en-US")}}
\\newcommand{\\BrowserBundleBytes}{${b.browserKernelMinifiedBytes.toLocaleString("en-US")}}
\\newcommand{\\BrowserBundleGzipBytes}{${b.browserKernelGzipBytes.toLocaleString("en-US")}}
\\newcommand{\\BrowserBundleBrotliBytes}{${b.browserKernelBrotliBytes.toLocaleString("en-US")}}
\\newcommand{\\WasmGzipBytes}{${b.wasmBinaryGzipBytes.toLocaleString("en-US")}}
\\newcommand{\\WasmBrotliBytes}{${b.wasmBinaryBrotliBytes.toLocaleString("en-US")}}
`;
mkdirSync("paper/manuscript", { recursive: true });
writeFileSync("paper/manuscript/generated-results.tex", tex, "utf8");
console.log(JSON.stringify(summary, null, 2));
